//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.08 at 05:20:24 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.neoflex.ru/xml/customers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.neoflex.xml.customers;
