//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 11:17:52 AM SAMT 
//


package ru.neoflex.xml.clientebm;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AddressType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ClientID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
        "address",
        "cityName",
        "regionName",
        "postal",
        "countryName"
})
public class AddressType {

    @XmlElement(name = "Address", required = true)
    protected String address;
    @XmlElement(name = "CityName", required = true)
    protected String cityName;
    @XmlElement(name = "RegionName", required = true)
    protected String regionName;
    @XmlElement(name = "Postal", required = true)
    protected String postal;
    @XmlElement(name = "CountryName", required = true)
    protected String countryName;
    @XmlAttribute(name = "ClientID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clientID;

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the cityName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the regionName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegionName(String value) {
        this.regionName = value;
    }

    /**
     * Gets the value of the postal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostal() {
        return postal;
    }

    /**
     * Sets the value of the postal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostal(String value) {
        this.postal = value;
    }

    /**
     * Gets the value of the countryName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the clientID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClientID(String value) {
        this.clientID = value;
    }

}
