//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 11:17:52 AM SAMT 
//


package ru.neoflex.xml.clientebm;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.StringJoiner;


/**
 * <p>Java class for OrderType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="EmpID" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Adds" type="{}AddsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderType", propOrder = {
        "clientId",
        "empID",
        "orderID",
        "date",
        "deliveryDate",
        "adds"
})
public class OrderType {

    @XmlElement(name = "ClientId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clientId;
    @XmlElement(name = "EmpID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String empID;
    @XmlElement(name = "OrderID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String orderID;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "Adds", required = true)
    protected AddsType adds;

    /**
     * Gets the value of the clientId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the empID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmpID() {
        return empID;
    }

    /**
     * Sets the value of the empID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmpID(String value) {
        this.empID = value;
    }

    /**
     * Gets the value of the orderID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the adds property.
     *
     * @return possible object is
     * {@link AddsType }
     */
    public AddsType getAdds() {
        return adds;
    }

    /**
     * Sets the value of the adds property.
     *
     * @param value allowed object is
     *              {@link AddsType }
     */
    public void setAdds(AddsType value) {
        this.adds = value;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", OrderType.class.getSimpleName() + "[", "]")
                .add("clientId='" + clientId + "'")
                .add("empID='" + empID + "'")
                .add("orderID='" + orderID + "'")
                .add("date=" + date)
                .add("deliveryDate=" + deliveryDate)
                .add("adds=" + adds)
                .toString();
    }
}
